all: hello-fork hello-system
	

hello-fork: hello-fork.cpp
	$(CXX) -g -o hello-fork hello-fork.cpp

hello-system: hello-system.cpp
	$(CXX) -g -o hello-system hello-system.cpp
	
clean:
	rm -f hello-fork hello-system

